version: "3.9"

services:
  nginx_prod:
    container_name: nginx_prod
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    restart: always
    ports:
      - "80:80"
    networks:
      - frontend_prod
    depends_on:
      - wordpress_prod

  db_prod:
    container_name: db_prod
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend_prod

  wordpress_prod:
    container_name: wordpress_prod
    depends_on:
      - db_prod
    image: wordpress:latest
    volumes:
      - ./wp_data/html:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_prod:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - frontend_prod
      - backend_prod

networks:
  frontend_prod: {}
  backend_prod: {}
