version: "3.9"

services:
  nginx_prod:
    build:
      context: ./prod/nginx
      dockerfile: Dockerfile
    volumes:
      - ./prod/nginx/conf.d:/etc/nginx/conf.d
    restart: always
    ports:
      - "8080:80"

  db_prod:
    image: mysql:5.7
    volumes:
      - ./prod/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress_prod:
    depends_on:
      - db_prod
    image: wordpress:latest
    volumes:
      - ./prod/wp_data/html:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_prod:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
